### ISSUE TITLE
Errors occur when only few viruses were detected. (VIRTUS_wrapper.py)

### ISSUE THREAD

**Issue by yyoshiaki** [yyoshiaki/VIRTUS2#1]
When we detected only a few viruses, the following error can occur.

```
Conducting Mann-Whitney U-test
Traceback (most recent call last):
  File "/home/yyasumizu/Programs/VIRTUS2/bin/VIRTUS_wrapper.py", line 217, in <module>
    fdr = pd.Series(multipletests(pval,method = "fdr_bh")[1], index = pval.index)
  File "/home/yyasumizu/anaconda3/lib/python3.8/site-packages/statsmodels/stats/multitest.py", line 147, in multipletests
    alphacSidak = 1 - np.power((1. - alphaf), 1./ntests)
ZeroDivisionError: float division by zero
```

run again with the lower thresholds such as;
`--th_cov 5 --th_rate 0.000001`

Note that, VIRTUS_wrapper.py can automatically intermediate files, therefore, users may be able to save time.

In the next release, we will add the patch for this issue.

**Comment by yyoshiaki** [comment]
fixed in #
